Update kind-install

diff --git a/kind-install b/kind-install
--- a/kind-install
+++ b/kind-install
@@ -15,18 +15,18 @@ fi
 # Check for hardware prerequisites
 mem_size=$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')
 if [[ $mem_size -lt 2097152 ]]; then
-  echo "Error: Your system does not meet the minimum memory requirement of 5GB for Minikube" >&2
+  echo "Error: Your system does not meet the minimum memory requirement of 2GB " >&2
   exit 1
 fi
 
 num_cpus=$(nproc)
 if [[ $num_cpus -lt 2 ]]; then
-  echo "Error: Your system does not meet the minimum CPU requirement of 2 cores for Minikube" >&2
+  echo "Error: Your system does not meet the minimum CPU requirement of 2 cores" >&2
   exit 1
 fi
 
 # Confirm with the user before proceeding
-read -p "Do you want to proceed with the installation of Minikube? (y/n) " -n 1 -r
+read -p "Do you want to proceed with the installation of KIND ? (y/n) " -n 1 -r
 echo   
 if [[ ! $REPLY =~ ^[Yy]$ ]]
 then
